### PR TITLE
Provide meson wrap for libxml++ 3.0.1.

### PR DESCRIPTION
**Pull request by talisein**

### CODE REVIEW

**Comment by jpakkane** [comment]
There is no need to do `join_paths('exceptions','exception.h')` for static content. If you do `exceptions/exception.h`, Meson will do the right thing for you and it is more readable. Join_paths is only needed either part of the join is dynamically generated.

Also, instead of installing the headers individually you might look into `install_subdir` instead.

**Comment by talisein** [comment]
The layout of this project has the header files in the same directory as the source files, so I think that if I install_subdir() I would only end up explicitly listing all of the source files in exclude_files.

**Comment by talisein** [comment]
ping

**Comment by jpakkane** [comment]
You should not have a wrap file for libxml here. The project should only say that it needs libxml, not how it should be provided. This way users of this wrap can choose themselves where they get libxml from.

Also having wrap files inside subprojects do nothing. They must always be at the top level project.

**Comment by talisein** [comment]
Removed, thanks. I misunderstood the documentation; I thought just circular dependencies were forbidden.

**Comment by talisein** [comment]
Thank you :)

**Pull request merged**
